export const navLinks = [
  {
    id: "",
    title: "INÍCIO",
  },
  {
    id: "servicos",
    title: "SERVIÇOS",
  },
  {
    id: "sobre-nos",
    title: "SOBRE NÓS",
  },
];

export const slider = [
  {
    id: 1,
    src: "/slide/SLIDE1.png",
  },
  {
    id: 2,
    src: "/slide/SLIDE2.png",
  },
  {
    id: 3,
    src: "/slide/SLIDE3.png",
  },
  {
    id: 4,
    src: "/slide/SLIDE4.png",
  },
  {
    id: 5,
    src: "/slide/SLIDE5.png",
  },
  {
    id: 6,
    src: "/slide/SLIDE6.png",
  },
];

export const especialistas = [
  {
    id: 11,
    src: "/especialistas/vinicius.png",
    name: "Dr. Vinicius Ferreira",
    cargo: "Biomédico",
    code: "CRBM - 7264",
  },
  {
    id: 10,
    src: "/especialistas/rogerio.png",
    name: "Dr. Rogério Rodrigues",
    cargo: "Cirurgião - Dentista",
    code: "CRO 7861 - CE",
  },
  {
    id: 9,
    src: "/especialistas/nise.png",
    name: "Dra. Nise Arruda",
    cargo: "Nutricionista",
    code: "CRN11 - 8540",
  },
  {
    id: 3,
    src: "/especialistas/italo.png",
    name: "Dr. Ítalo Cavalcante",
    cargo: "Médico Nutrólogo",
    code: "CRM - 19389",
  },
  {
    id: 6,
    src: "/especialistas/larissa.png",
    name: "Dra. Larissa Almeida",
    cargo: "Biomédica",
    code: "CRM - 19389",
  },
  {
    id: 7,
    src: "/especialistas/mayra.png",
    name: "Dra. Mayra Saboia",
    cargo: "Médica Dermatologista",
    code: "CRM - 16956",
  },
  {
    id: 2,
    src: "/especialistas/erico.png",
    name: "Dr. Érico Brasil",
    cargo: "Médico - Cirurgião Plástico",
    code: "",
  },
  {
    id: 8,
    src: "/especialistas/naira.png",
    name: "Dra. Naira Thaís",
    cargo: "Fisioterapeuta",
    code: "CREFITO 6: 334.704-F",
  },
  {
    id: 1,
    src: "/especialistas/bianca.png",
    name: "Bianca Januário",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
  {
    id: 4,
    src: "/especialistas/jardian.png",
    name: "Jardyan Dantas",
    cargo: "Massoterapeuta",
    code: "",
  },
  {
    id: 5,
    src: "/especialistas/kelliane.png",
    name: "Kelliane Silva",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
  {
    id: 11,
    src: "/especialistas/vanessa.png",
    name: "Vanessa Santos",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
];

export const servicos = [
  {
    id: 1,
    titulo: "DAY SPA FAMÍLIA RENNOVI",
    desc: "Um momento especial, criado para aproveitar o que há de mais relaxante ao lado das pessoas que você mais ama. (Day spa para até 4 pessoas).",
    serv: "Boas Vindas + SPA dos Pés e das Mãos + Aromático + Banho Aromático com Hidromassagem e Cromoterapia + Facial Personalizado + Massagem Relaxante + Lanche leve acompanhado de suco saboroso.",
    duracao: "3H",
    valor: 430,
    img: "/servicos/day-spa-familia.png",
    filterId: 1,
  },
  {
    id: 2,
    titulo: "DAY SPA ROMÂNTICO",
    desc: "Para casais que querem aproveitar um momento especial juntos, relaxando em clima de romance.",
    serv: "Banho Romântico com Espuma, Hidromassagem e Cromoterapia + Massagem Casal Aromática Envolvente + Chocolate Afrodisíaco e Espumante.",
    duracao: "2H30",
    valor: 285,
    img: "/servicos/day-spa-romantico.png",
    filterId: 1,
  },
  {
    id: 3,
    titulo: "DAY SPA NOIVO",
    desc: null,
    serv: "Boas Vindas + Banho quente com Esfoliação Corporal + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Rubi + Revitalização dos Pés e Mãos + Lavagem capilar terapêutica + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 718,
    img: "/servicos/day-spa-noivo.png",
    filterId: 1,
  },
  {
    id: 4,
    titulo: "DAY SPA NOIVA",
    desc: null,
    serv: "Boas Vindas + Banho quente com Esfoliação Corporal Dama da Noite + Day spa luxuoso corpo dourado + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Rubi + Revitalização dos Pés e Mãos + Lavagem capilar relaxante + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 997,
    img: "/servicos/day-spa-noiva.png",
    filterId: 1,
  },
  {
    id: 5,
    titulo: "DAY SPA NOIVA + ACOMPANHANTE",
    desc: null,
    serv: "A noiva + acompanhante: Boas Vindas + Banho quente com Esfoliação Corporal Dama da Noite + Day spa luxuoso corpo dourado + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Diamante + Revitalização dos Pés e Mãos + Lavagem capilar relaxante Grandha + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 1397,
    img: "/servicos/day-spa-noiva-acompanhante.png",
    filterId: 1,
  },
  {
    id: 6,
    titulo: "KIDS MASSAGEM",
    desc: "As crianças adoram. Relaxam e se divertem enquanto recebem uma massagem especial.",
    serv: null,
    duracao: "40M",
    valor: 80,
    img: "/servicos/kids-massagem.png",
    filterId: 2,
  },
  {
    id: 7,
    titulo: "MASSAGEM SLIM BAMBU",
    desc: "Associação de massagem modeladora e bambuterapia com princípios ativos que ajudam na ativação da circulação e potencializam os resultados. Excelente massagem para modelagem corporal.",
    serv: null,
    duracao: "1H",
    valor: 100,
    img: "/servicos/slim-bambu.png",
    filterId: 2,
  },
  {
    id: 9,
    titulo: "MASSAGEM TERAPÊUTICA",
    desc: "Tem efeitos surpreendentes nas regiões do corpo de maior tensão e dores musculares. Utiliza-se de manobras para ativar a circulação, liberar a fáscia e relaxar a musculatura.",
    serv: null,
    duracao: "1H",
    valor: 100,
    img: "/servicos/massagem-terapeutica.png",
    filterId: 2,
  },
  {
    id: 8,
    titulo: "TERAPIA DE PEDRAS QUENTES",
    desc: "A terapia de Pedras Quentes combina técnicas terapêuticas de manipulação, óleos quentes e aromaterapia. Essas técnicas proporcionam alívio da tensão muscular, permitindo alcançar uma profunda sensação de prazer, relaxamento e bem-estar.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/pedras-quentes.png",
    filterId: 4,
  },

  {
    id: 10,
    titulo: "DRENAGEM LINFÁTICA",
    desc: "A Drenagem Linfática Manual é um tipo de massagem que utiliza manobras leves, suaves, rítmicas, lentas e precisas, visando otimizar as funções do sistema linfático.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/drenagem-linfatica.png",
    filterId: 4,
  },
  {
    id: 11,
    titulo: "LIMPEZA DE PELE",
    desc: "Com uma ação imediata e duradoura, este tratamento retarda o envelhecimento da cútis, higieniza profundamente, promove a renovação celular, a nutrição e o controle da produção seborreica e acneica.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/limpeza-pele.png",
    filterId: 4,
  },
  {
    id: 12,
    titulo: "MASSAGEM RELAXANTE COM VENTOSAS",
    desc: "A terapia com ventosas combina técnicas terapêuticas de manipulação, óleos quentes e aromaterapia. Essas técnicas proporcionam alívio da tensão muscular, permitindo alcançar uma profunda sensação de prazer, relaxamento e bem estar.",
    serv: null,
    duracao: "1H",
    valor: 120,
    img: "/servicos/ventosas.png",
    filterId: 2,
  },
  {
    id: 13,
    titulo: "BANHO OCEANIA",
    desc: "É um banho tonificante, refrescante e rejuvenescedor, que fortalece o sistema imunológico e melhora a circulação. Rico em algas marinhas na composição dos óleos essenciais, é um banho perfeito para quem busca uma pele mais firme e elástica.",
    serv: null,
    duracao: "30M",
    valor: 110,
    img: "/servicos/banho-oceania.png",
    filterId: 4,
  },
  {
    id: 14,
    titulo: "LAVAGEM TERAPÊUTICA",
    desc: "Indicado para higienizar profundamente o couro cabeludo e cabelos e preparar para tratamentos injetáveis.",
    serv: "Sauna capilar, e cromoterapia, higienização e esfoliaçao do couro cabeludo com a linha Grandha spa, altafrequência e ledterapia.",
    duracao: "1H30",
    valor: 100,
    img: "/servicos/lavagem-terapeutica.png",
    filterId: 3,
  },
  {
    id: 15,
    titulo: "PEELING CAPILAR",
    desc: "Ritual capilar indicado para higienização profunda do couro cabeludo com seborreia e caspas que melhora a circulação sanguínea trazendo nutrientes para a região, hidratação e fortalecimento dos fios com geoterapia, alta frequência e óleo de melaleuca.",
    serv: null,
    duracao: "2H",
    valor: 150,
    img: "/servicos/peeling-capilar.png",
    filterId: 3,
  },
  {
    id: 16,
    titulo: "CRONOGRAMA CAPILAR",
    desc: "Sequência de tratamentos terapêuticos para recuperar a hidratação, nutrição e saude dos cabelos. Indicado para cabelos danificados por química. (5 sessões/ semanais)",
    serv: null,
    duracao: "1H30",
    valor: 549,
    img: "/servicos/cronograma-capilar.png",
    filterId: 3,
  },
  {
    id: 17,
    titulo:
      "TRATAMENTOS CAPILARES REALIZADOS MEDIANTE CONSULTA COM ESPECIALISTA.",
    desc: "• Dermatite e focos inflamatorios no couro cabeludo;\n• Alopecia androgenética;\n• Focos inflamatórios e crostas em Mega Hair;\n• Queda de cabelo por estresse e/ou ansiedade;\n• Cabelos danificados por química.",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/tratamentos-capilares.png",
    filterId: 3,
  },
];

// especificacoes filtros
// 1 - Day Spa
// 2 - Massagem
// 3 - Tratamentos capilares
// 4 - Relaxamento
