export const navLinks = [
  {
    id: "",
    title: "INÍCIO",
  },
  {
    id: "servicos",
    title: "SERVIÇOS",
    dropdown: [
      { id: "dermatologia", title: "DERMATOLOGIA" },
      { id: "estetica-avancada", title: "ESTÉTICA AVANÇADA" },
      { id: "depilacao-feminina", title: "DEPILAÇÃO A LASER - FEMININO" },
      { id: "depilacao-masculina", title: "DEPILAÇÃO A LASER - MASCULINO" },
      { id: "odontologia", title: "ODONTOLOGIA" },
      { id: "the-spa", title: "SPA" },
      { id: "terapia-capilar", title: "TERAPIA CAPILAR" },
      { id: "nutricao", title: "NUTRIÇÃO" },
      { id: "nutrologia", title: "NUTROLOGIA" },
    ],
  },
  {
    id: "sobre-nos",
    title: "SOBRE NÓS",
  },
];

// Slider das máquinas
export const slider = [
  {
    id: 1,
    src: "/slide/SLIDE1.png",
  },
  {
    id: 2,
    src: "/slide/SLIDE2.png",
  },
  {
    id: 3,
    src: "/slide/SLIDE3.png",
  },
  {
    id: 4,
    src: "/slide/SLIDE4.png",
  },
  {
    id: 5,
    src: "/slide/SLIDE5.png",
  },
  {
    id: 6,
    src: "/slide/SLIDE6.png",
  },
  {
    id: 7,
    src: "/slide/SLIDE7.png",
  },
];
// Slider dos especialistas
export const especialistas = [
  {
    id: 11,
    src: "/especialistas/vinicius.png",
    name: "Dr. Vinicius Ferreira",
    cargo: "Biomédico",
    code: "CRBM - 7264",
  },
  {
    id: 10,
    src: "/especialistas/rogerio.png",
    name: "Dr. Rogério Rodrigues",
    cargo: "Cirurgião - Dentista",
    code: "CRO 7861 - CE",
  },
  {
    id: 9,
    src: "/especialistas/nise.png",
    name: "Dra. Nise Arruda",
    cargo: "Nutricionista",
    code: "CRN11 - 8540",
  },
  {
    id: 3,
    src: "/especialistas/italo.png",
    name: "Dr. Ítalo Cavalcante",
    cargo: "Médico Nutrólogo",
    code: "CRM - 19389",
  },
  {
    id: 6,
    src: "/especialistas/larissa.png",
    name: "Dra. Larissa Almeida",
    cargo: "Biomédica",
    code: "CRM - 19389",
  },
  {
    id: 7,
    src: "/especialistas/mayra.png",
    name: "Dra. Mayra Saboia",
    cargo: "Médica Dermatologista",
    code: "CRM - 16956",
  },
  {
    id: 2,
    src: "/especialistas/erico.png",
    name: "Dr. Érico Brasil",
    cargo: "Médico - Cirurgião Plástico",
    code: "",
  },
  {
    id: 8,
    src: "/especialistas/naira.png",
    name: "Dra. Naira Thaís",
    cargo: "Fisioterapeuta",
    code: "CREFITO 6: 334.704-F",
  },
  {
    id: 1,
    src: "/especialistas/bianca.png",
    name: "Bianca Januário",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
  {
    id: 4,
    src: "/especialistas/jardian.png",
    name: "Jardyan Dantas",
    cargo: "Massoterapeuta",
    code: "",
  },
  {
    id: 5,
    src: "/especialistas/kelliane.png",
    name: "Kelliane Silva",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
  {
    id: 11,
    src: "/especialistas/vanessa.png",
    name: "Vanessa Santos",
    cargo: "Esteticista Cosmetóloga",
    code: "",
  },
];

export const servicos = [
  {
    id: 1,
    titulo: "DAY SPA FAMÍLIA RENNOVI",
    desc: "Um momento especial, criado para aproveitar o que há de mais relaxante ao lado das pessoas que você mais ama. (Day spa para até 4 pessoas).",
    serv: "Boas Vindas + SPA dos Pés e das Mãos + Aromático + Banho Aromático com Hidromassagem e Cromoterapia + Facial Personalizado + Massagem Relaxante + Lanche leve acompanhado de suco saboroso.",
    duracao: "3H",
    valor: 430,
    img: "/servicos/day-spa-familia.png",
    filterId: "the-spa",
  },
  {
    id: 2,
    titulo: "DAY SPA ROMÂNTICO",
    desc: "Para casais que querem aproveitar um momento especial juntos, relaxando em clima de romance.",
    serv: "Banho Romântico com Espuma, Hidromassagem e Cromoterapia + Massagem Casal Aromática Envolvente + Chocolate Afrodisíaco e Espumante.",
    duracao: "2H30",
    valor: 285,
    img: "/servicos/day-spa-romantico.png",
    filterId: "the-spa",
  },
  {
    id: 3,
    titulo: "DAY SPA NOIVO",
    desc: null,
    serv: "Boas Vindas + Banho quente com Esfoliação Corporal + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Rubi + Revitalização dos Pés e Mãos + Lavagem capilar terapêutica + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 718,
    img: "/servicos/day-spa-noivo.png",
    filterId: "the-spa",
  },
  {
    id: 4,
    titulo: "DAY SPA NOIVA",
    desc: null,
    serv: "Boas Vindas + Banho quente com Esfoliação Corporal Dama da Noite + Day spa luxuoso corpo dourado + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Rubi + Revitalização dos Pés e Mãos + Lavagem capilar relaxante + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 997,
    img: "/servicos/day-spa-noiva.png",
    filterId: "the-spa",
  },
  {
    id: 5,
    titulo: "DAY SPA NOIVA + ACOMPANHANTE",
    desc: null,
    serv: "A noiva + acompanhante: Boas Vindas + Banho quente com Esfoliação Corporal Dama da Noite + Day spa luxuoso corpo dourado + Hidromassagem com sais de banho e espuma deliciosa e pétalas de rosas + Almoço/Janta/Lanche saudável e saboroso + Massagem com pedras quentes + Limpeza de pele + Revitalização Facial com Máscara de Diamante + Revitalização dos Pés e Mãos + Lavagem capilar relaxante Grandha + Finalização com Espumante e morangos.",
    duracao: "6H",
    valor: 1397,
    img: "/servicos/day-spa-noiva-acompanhante.png",
    filterId: "the-spa",
  },
  {
    id: 6,
    titulo: "KIDS MASSAGEM",
    desc: "As crianças adoram. Relaxam e se divertem enquanto recebem uma massagem especial.",
    serv: null,
    duracao: "40M",
    valor: 80,
    img: "/servicos/kids-massagem.png",
    filterId: "the-spa",
  },
  {
    id: 7,
    titulo: "MASSAGEM SLIM BAMBU",
    desc: "Associação de massagem modeladora e bambuterapia com princípios ativos que ajudam na ativação da circulação e potencializam os resultados. Excelente massagem para modelagem corporal.",
    serv: null,
    duracao: "1H",
    valor: 100,
    img: "/servicos/slim-bambu.png",
    filterId: "the-spa",
  },
  {
    id: 9,
    titulo: "MASSAGEM TERAPÊUTICA",
    desc: "Tem efeitos surpreendentes nas regiões do corpo de maior tensão e dores musculares. Utiliza-se de manobras para ativar a circulação, liberar a fáscia e relaxar a musculatura.",
    serv: null,
    duracao: "1H",
    valor: 100,
    img: "/servicos/massagem-terapeutica.png",
    filterId: "the-spa",
  },
  {
    id: 8,
    titulo: "TERAPIA DE PEDRAS QUENTES",
    desc: "A terapia de Pedras Quentes combina técnicas terapêuticas de manipulação, óleos quentes e aromaterapia. Essas técnicas proporcionam alívio da tensão muscular, permitindo alcançar uma profunda sensação de prazer, relaxamento e bem-estar.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/pedras-quentes.png",
    filterId: "the-spa",
  },

  {
    id: 10,
    titulo: "DRENAGEM LINFÁTICA",
    desc: "A Drenagem Linfática Manual é um tipo de massagem que utiliza manobras leves, suaves, rítmicas, lentas e precisas, visando otimizar as funções do sistema linfático.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/drenagem-linfatica.png",
    filterId: "the-spa",
  },
  {
    id: 11,
    titulo: "LIMPEZA DE PELE",
    desc: "Com uma ação imediata e duradoura, este tratamento retarda o envelhecimento da cútis, higieniza profundamente, promove a renovação celular, a nutrição e o controle da produção seborreica e acneica.",
    serv: null,
    duracao: "1H30",
    valor: 120,
    img: "/servicos/limpeza-pele.png",
    filterId: "the-spa",
  },
  {
    id: 12,
    titulo: "MASSAGEM RELAXANTE COM VENTOSAS",
    desc: "A terapia com ventosas combina técnicas terapêuticas de manipulação, óleos quentes e aromaterapia. Essas técnicas proporcionam alívio da tensão muscular, permitindo alcançar uma profunda sensação de prazer, relaxamento e bem estar.",
    serv: null,
    duracao: "1H",
    valor: 120,
    img: "/servicos/ventosas.png",
    filterId: "the-spa",
  },
  {
    id: 13,
    titulo: "BANHO OCEANIA",
    desc: "É um banho tonificante, refrescante e rejuvenescedor, que fortalece o sistema imunológico e melhora a circulação. Rico em algas marinhas na composição dos óleos essenciais, é um banho perfeito para quem busca uma pele mais firme e elástica.",
    serv: null,
    duracao: "30M",
    valor: 110,
    img: "/servicos/banho-oceania.png",
    filterId: "the-spa",
  },
  // Dermatologia
  {
    id: 18,
    titulo: "CONSULTA DERMATOLÓGICA",
    desc: "O dermatologista é o médico responsável pelo tratamento e prevenção de doenças da pele, pelos, cabelos e unhas. Além disso, este médico orienta seus pacientes sobre cuidados gerais com a pele e realiza procedimentos estéticos.",
    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/dermatologia2.png",
    filterId: "dermatologia",
  },
  {
    id: 19,
    titulo: "CIRURGIA DERMATOLÓGICA",
    desc: "A Cirurgia Dermatológica é a área da Dermatologia especializada em procedimentos diagnósticos, cirúrgicos, estéticos e oncológicos realizados na pele ou no tecido celular subcutâneo, que têm por objetivo prevenir, restaurar e manter a saúde de sua pele, cabelo ou unhas.",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/dermatologia.png",
    filterId: "dermatologia",
  },
  //ESTÉTICA AVANÇADA
  {
    id: 20,
    titulo: "HARMONIZAÇÃO FACIAL",
    desc: "Área da estética que cuida do embelezamento facial com foco na jovialidade. Botox, Preenchimento, Bioestimuladores de Colágeno, Fios de sustentação, Lipoquimica de Papada, Skinbooster, Mesoterapia.",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/harmonizacao3.png",
    filterId: "estetica-avancada",
  },
  {
    id: 21,
    titulo: "HARMONIZAÇÃO CORPORAL E ÍNTIMA",
    desc: "Área da Estética que visa tratar disfunções estéticas corporais e proporcionar o rejuvenescimento. Tratamento de celulite, Flacidez e Gordura Localizada, Preenchimento Corporal",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/harmonizacao2.png",
    filterId: "estetica-avancada",
  },
  {
    id: 22,
    titulo: "TECNOLOGIAS AVANÇADAS",
    desc: "A Rennovi® é pioneira em tecnologias estéticas que proporcionam resultados de alta performance no embelezamento da face e corpo. ATRIA, LASER SOLON VISIONARY, ÔNIX DUET, CRIODERMIS, LIGHT PULSE.",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/harmonizacao.png",
    filterId: "estetica-avancada",
  },
  // DEPILAÇÃO FEMININO
  {
    id: 23,
    titulo: "BUÇO",
    desc: "Processo de depilação do buço feminino por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",
    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/buco.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 24,
    titulo: "QUEIXO",
    desc: "Processo de depilação do queixo feminino por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/queixo.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 25,
    titulo: "FACE",
    desc: "Processo de depilação da face feminina por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 120,
    img: "/servicos/face.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 26,
    titulo: "AXILA",
    desc: "Processo de depilação das axilas femininas por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 90,
    img: "/servicos/axila.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 27,
    titulo: "ANTEBRAÇO",
    desc: "Processo de depilação do antebraço feminino por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 150,
    img: "/servicos/antebraco.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 28,
    titulo: "LINHA ALBA",
    desc: "Processo de depilação da linha alba feminina por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/alba.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 29,
    titulo: "VIRILHA SIMPLES",
    desc: "Processo de depilação simples de virilha feminina por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 100,
    img: "/servicos/virilhasimples.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 30,
    titulo: "VIRILHA COMPLETA",
    desc: "Processo de depilação completa da virilha feminina por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 150,
    img: "/servicos/virilhacompleta.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 31,
    titulo: "COXAS",
    desc: "Processo de depilação de coxas femininas por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 300,
    img: "/servicos/coxas.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 32,
    titulo: "PERNA",
    desc: "Processo de depilação de pernas femininas por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 250,
    img: "/servicos/perna.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 33,
    titulo: "COXA + PERNA",
    desc: "Processo de depilação de coxa e perna feminina por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 500,
    img: "/servicos/coxaeperna.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 34,
    titulo: "PÉ + DEDO",
    desc: "Processo de depilação de pés e dedos femininos por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/pé.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 35,
    titulo: "GLÚTEOS",
    desc: "Processo de depilação dos glúteos femininos por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 150,
    img: "/servicos/gluteos.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 36,
    titulo: "ARÉOLAS",
    desc: "Processo de depilação das aréolas femininas por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/areola.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 37,
    titulo: "MÃOS + DEDOS",
    desc: "Processo de depilação de mãos e dedos femininos por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/mao.png",
    filterId: "depilacao-feminina",
  },
  {
    id: 38,
    titulo: "ENTRE SOBRANCELHAS",
    desc: "Processo de depilação entre sobrancelhas feminino por meio de laser que destroem o folículo piloso que proporciona resultados duradouros com manutenções anuais. Nossa tecnologia pioneira remove até 80% dos pelos na primeira sessão.",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/sobrancelha.png",
    filterId: "depilacao-feminina",
  },
  // DEPILAÇÃO MASCULINO
  {
    id: 39,
    titulo: "BARBA COMPLETA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 250,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 40,
    titulo: "COSTELETAS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 90,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 41,
    titulo: "PESCOÇO",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 130,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 42,
    titulo: "ORELHAS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 50,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 43,
    titulo: "ENTRE SOBRANCELHAS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 40,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 44,
    titulo: "AXILA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 100,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 45,
    titulo: "BRAÇO",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 150,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 46,
    titulo: "OMBRO",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 200,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 47,
    titulo: "PEITO",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 250,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 48,
    titulo: "COSTAS INTEIRA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 500,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 49,
    titulo: "COSTAS SUPERIOR",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 300,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 50,
    titulo: "COXA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 300,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 51,
    titulo: "PERNA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 300,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 52,
    titulo: "COXA + PERNA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 550,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  {
    id: 53,
    titulo: "GLÚTEOS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 190,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "depilacao-masculina",
  },
  // ODONTOLOGIA
  {
    id: 54,
    titulo: "CLÍNICA GERAL",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  {
    id: 55,
    titulo: "IMPLANTES DENTÁRIOS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  {
    id: 56,
    titulo: "PRÓTESES DENTÁRIAS",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  {
    id: 57,
    titulo: "ORTODONTIA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  {
    id: 58,
    titulo: "PACIENTES ESPECIAIS",
    desc: "Down, Altista, Hipertensos, Diabéticos, Hipercolesterolemia.",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  {
    id: 59,
    titulo: "ESTÉTICA DO SORRISO",
    desc: "Clareamento Dental, Facetas de Resina e Porcelana, Bichectomia, Gengivoplastia, Restaurações Estéticas.",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "odontologia",
  },
  // ADICIONAR DO SPA POR QUE FALTOU
  {
    id: 60,
    titulo: "PELLING FACIAL",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "the-spa",
  },
  {
    id: 61,
    titulo: "RADIOFREQUÊNCIA FACIAL",
    desc: "",

    serv: null,
    duracao: "-",
    valor: "--",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "the-spa",
  },
  // TERAPIA CAPILAR
  {
    id: 14,
    titulo: "AVALIAÇÃO DO CABELO",
    desc: "Procedimento de avaliação completa do fio, possibilitando a descoberta de toda e qualquer disfunção do dele ou do couro cabeludo, seja oleosidade, ressecamento, falta de volume, volume em excesso, caspa e uma série de outras questões.",

    serv: null,
    duracao: "-",
    valor: "GRATUITO",
    img: "/servicos/avaliacao.png",
    filterId: "terapia-capilar",
  },
  {
    id: 63,
    titulo: "DETOX CAPILAR",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 120,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "terapia-capilar",
  },
  {
    id: 64,
    titulo: "MICROAGULHAMENTO CAPILAR",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 250,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "terapia-capilar",
  },
  {
    id: 65,
    titulo: "REPOSIÇÃO HÍDRICA E LIPÍDICA",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 100,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "terapia-capilar",
  },
  {
    id: 66,
    titulo: "MESOTERAPIA CAPILAR (INFUSÃO DE MEDICAMENTOS)",
    desc: "",

    serv: null,
    duracao: "-",
    valor: 300,
    img: "/servicos/tratamentos-capilares.png",
    filterId: "terapia-capilar",
  },
  // NUTRIÇÃO
  {
    id: 67,
    titulo: "PLANO ALIMENTAR PERSONALIZADO",
    desc: " Especialidade da nutrição que visa uma melhor estética do paciente com a conduta nutricional aplicada. Emagrecimento, Nutrição Esportiva e Nutrição Clínica Funcional.",

    serv: null,
    duracao: "--",
    valor: "--",
    img: "/servicos/alimentar.png",
    filterId: "nutricao",
  },
  // NUTROLOGIA
  {
    id: 68,
    titulo: "NUTROLOGIA",
    desc: "Nutrologia é a especialidade médica clínica que se dedica ao diagnóstico, prevenção e tratamento de doenças do comportamento alimentar. Emagrecimento, Hipertrofia, Implantes Hormonais.",

    serv: null,
    duracao: "--",
    valor: "--",
    img: "/servicos/nutrologa.png",
    filterId: "nutrologia",
  },
  {
    id: 69,
    titulo: "LAVAGEM TERAPÊUTICA",
    desc: "Indicado para higienizar profundamente o couro cabeludo e cabelos e preparar para tratamentos injetáveis.",
    serv: "Sauna capilar, e cromoterapia, higienização e esfoliaçao do couro cabeludo com a linha Grandha spa, altafrequência e ledterapia.",
    duracao: "1H30",
    valor: 100,
    img: "/servicos/lavagem-terapeutica.png",
    filterId: "terapia-capilar",
  },
  {
    id: 62,
    titulo: "PEELING CAPILAR",
    desc: "Ritual capilar indicado para higienização profunda do couro cabeludo com seborreia e caspas que melhora a circulação sanguínea trazendo nutrientes para a região, hidratação e fortalecimento dos fios com geoterapia, alta frequência e óleo de melaleuca.",
    serv: null,
    duracao: "2H",
    valor: 150,
    img: "/servicos/peeling-capilar.png",
    filterId: "terapia-capilar",
  },
  {
    id: 16,
    titulo: "CRONOGRAMA CAPILAR",
    desc: "Sequência de tratamentos terapêuticos para recuperar a hidratação, nutrição e saude dos cabelos. Indicado para cabelos danificados por química. (5 sessões/ semanais)",
    serv: null,
    duracao: "1H30",
    valor: 549,
    img: "/servicos/cronograma-capilar.png",
    filterId: "terapia-capilar",
  },
  {
    id: 17,
    titulo:
      "TRATAMENTOS CAPILARES REALIZADOS MEDIANTE CONSULTA COM ESPECIALISTA.",
    desc: "• Dermatite e focos inflamatorios no couro cabeludo;\n• Alopecia androgenética;\n• Focos inflamatórios e crostas em Mega Hair;\n• Queda de cabelo por estresse e/ou ansiedade;\n• Cabelos danificados por química.",

    serv: null,
    duracao: "-",
    valor: "-",
    img: "/servicos/tratamentos-capilares.png",
    filterId: "terapia-capilar",
  },
];
